### ISSUE TITLE
Request: Print an error when being ratelimited

### ISSUE THREAD

**Issue by williamhammond** [marcelja/facebook-delete#5]
I noticed after running the script for a while that I started get 0 events for everything. I assumed I was getting ratelimited but all the requests were still returning `200`'s. Eventually I took a peek at the response body and saw the message 

> We limit how often you can post, comment or do other things in a given amount of time in order to help protect the community from spam. You can try again later

In a div. If you'd like I can try and patch this to give a cleaner error message. I'd like some advice though, right now my only thought is to just search for a portion of that string in the body which doesn't seem ideal.

Thanks by the way. I've tried to use a bunch of tools trying to solve this problem and yours is the only one that works, and it works great :)

**Comment by marcelja** [comment]
Thanks for the insight! Yeah, giving a better error message should be implemented

**Comment by jeromescuggs** [comment]
for what it's worth, running one type of content at a time (you can still do it for all months and years you'd like) seems to have made my runs far more effective. 

still seemed to miss a few some every so often, but honestly i can't complain as it still took all of a few minutes to run it through all my comments made totaling a span of like 12 years, re-run to get any stragglers, and then repeat this for posts and then likes/reactions. 

as an alternative to a ratelimit warn, i might poke around and see about simply automating this 'run-then-rerun' step as a janky way to deeply clean 

but echoing OP.. this is the first non-intrusive and successful tool i've seen to purge a veritable ticking time-bomb of content. it's been a very tiny source of panic because a friend dug up the sort of foul stuff we were writing far before anyone thought parents and teachers would one day also be reading all that stuff... not anymore!  :)
