### ISSUE TITLE
Not deleting anything

### ISSUE THREAD

**Issue by BTolbert65** [marcelja/facebook-delete#6]
Facebook may have changed something on their end, deleter.go is no longer finding any elements to delete.

Searching elements from 2020:
Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec   Elements found:       0
Deleting elements from 2020:
0 [________________________________________________________________________________________________________________________________________________________________________________________] ?% ? p/s 0s

**Comment by marcelja** [comment]
It doesn't seem that anything was changed.

I fixed a bug on master. Could you try if that solves the problem?

**Comment by BTolbert65** [comment]
i tried the new update, still no luck.  I wonder if this isn't also a rate-limiting issue?  It's finding zero elements to delete.

**Comment by BTolbert65** [comment]
Are there any debug commands I can run for you?

**Comment by williamhammond** [comment]
You could potentially be running into https://github.com/marcelja/facebook-delete/issues/5

**Comment by williamhammond** [comment]
@BTolbert65 i found it by throwing print statements here https://github.com/marcelja/facebook-delete/blob/master/deleter.go#L60-L86 specifically https://github.com/marcelja/facebook-delete/blob/master/deleter.go#L85. Since Facebook doesn't give a good API for doing this stuff, regardless of what's happening really Facebook is going to return a 200, so i was just control-f'ing the body as I printed them out. It'll make your life a little easier if you only choose one year and category while debugging

**Comment by BTolbert65** [comment]
Whatever update was made last evening resolved this issue.
